runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: admin
  CLOUD_SQL_DATABASE_NAME: fit5120
  CLOUD_SQL_CONNECTION_NAME: heart-station-monash:us-east4:fit5120

handlers:
- url: /.*
  script: auto